'\" 
.\"     Title: shaman
.\"    Author: [Sam Stuewe]
.\"      Date: 2013-08-02
.\"  Language: English
.\"
.TH "SHAMAN" "1" "2013-08-02" "\ \& 0\&.2" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.\"
.\" <- Main Content ->
.SH "NAME"
shaman \- Fetch basic weather information from the NOAA
.SH "SYNOPSIS"
.B shaman
.BR [ options ]
.I "location"
.SH "DESCRIPTION"
.sp
.B shaman 
is a simple CLI to fetch basic weather information about a given location from the NOAA using 
.BR curl (1). 
.sp
Though more flexible specification is planned, at the moment,
.IR location " can only be in the form of a zip code\&. "
.SH "CONFIGURATION"
A configuration file may be placed at
.IR "$XDG_CONFIG_HOME/shaman/config" " or at " "$HOME/.shamanrc"
which allows for setting a default location and/or selecting whether to print in metric or Imperial units. These settings are defined like so:
.RS

Location=<zipcode>

Units=<M|I>
.RE
.SH "PLANNED FEATURES"
7-day forecasts
.SH "OPTIONS"
.sp
.IP -a
Display all available information\&. Equivalent to -cdprtvw\&. Assumed if no options are passed\&.
.IP -c
Display current weather conditions\&.
.IP -d
Display humidity and dew point\&.
.IP -i
Display units in Imperial measurements\&. (default)
.IP -m
Display units in metric measurements\&.
.IP -p
Display pressure\&.
.IP -r
Display information about the reporting information center\&.
.IP -t
Display temperature\&.
.IP -v
Display visibility\&.
.IP -w
Display wind information\&.
.SH "AUTHOR"
Sam Stuewe <halosghost at archlinux dot info>
.SH "SEE ALSO"
.BR curl (1)
